log_dir: "Checkpoint"
save_freq: 1
device: "cuda"
epochs: 100
batch_size: 16
pretrained_model: ""
train_data: "Data/train_list.txt"
val_data: "Data/val_list.txt"

preprocess_params:
  sr: 44100
  spect_params:
    n_fft: 2048
    win_length: 2048
    hop_length: 512
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 178
   token_embedding_dim: 512

optimizer_params:
  lr: 0.001
